SIF_IMAGE=$1
TRAINING_SCRIPT=$2
BACKEND=$3
NPROCS="16"
HOSTS="gr13b05n05:8,gr13b05n06:8"
COMMAND="python $TRAINING_SCRIPT --backend $BACKEND"

export MASTER_ADDR="gr13b05n05"
export MASTER_PORT="12345"

mpirun -x MASTER_ADDR -x MASTER_PORT --np $NPROCS --host $HOSTS apptainer exec --nv $SIF_IMAGE $COMMAND
